#!/bin/bash

app_creator="GCYOXCBLUWFJMRH4B6TGL2HO5RB6SW3ZTOREXCIIY7ERVJGYZ463QPG7QU"
guest="6JTXVG2MDQL7W5I77RCA62C5OTBZLYTPVHXC43RFNGEKTCAHMQAMHNJ2AE"
service="F66DD432HVSH5MOU4RCD3WOLNK4VQO4GT4RBZ3KGZE7GBNQZE65HVUSLGA"

metadata_hash="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
asset_name="Apartment"
unit_name="Suite"
url="https://www.airbnb.com/rooms/676672101230669000?check_in=2023-10-18&check_out=2023-10-19&source_impression_id=p3_1697594568_8QjpZP9PPxn0GxaU&previous_page_section_name=1000&federated_search_id=9145957b-d172-441f-a51d-bcbd2852f999"
rental=10
deposit=3



#create app
function create_app {
    goal app create --clear-prog clear.teal --approval-prog approval.teal --local-byteslices 2 --local-ints 0 --global-ints 6 --global-byteslices 0 --creator $app_creator'
}

function setup_app {
    #setup app and create asset
    goal app call -n "SETUP" --app-id "$app_id" --app-arg "str:$metadata_hash" \
        --app-arg "str:$asset_name" --app-arg "str:$unit_name" \
        --app-arg "str:$rental" --app-arg "str:$deposit" --out setup_txn.txn --from $app_creator
 
    goal clerk send --from="$app_creator" --to="$app_addr" --amount=400000 --out seedcontract.txn 
    cat seedcontract.txn setup_txn.txn > combined.txn
    goal clerk group -i combined.txn -o group_txn_setup.txn 
    goal clerk split -i group_txn_setup.txn -o splitted.txn 
    goal clerk sign -i splitted-0.txn -o signout-0.txn 
    goal clerk sign -i splitted-1.txn -o signout-1.txn && cat signout-0.txn signout-1.txn > setup.txn
    goal clerk dryrun -t setup.txn -o setup.debug --dryrun-dump
    goal clerk rawsend -f setup.txn
}

function retrieve_asset_info {
    goal app read --app-id $app_id --global | grep 'ui' | head -n 1 | awk -F ": " '{print $2}'
}

function optin_routine {
    # opt into ASA and Smart Contract
    goal asset send -a 0 --assetid $asset_id  -f $guest -t $guest --creator $app_addr
    goal app optin --app-id "$app_id" --from "$guest"
    goal app optin --app-id "$app_id" --from "$guest"  --dryrun-dump --out app_optin_txn 
}

function algo_payment {
    # algo hand in - VALID
    goal app call --app-id "$app_id" --from "$guest" --note "ALGO_PAYMENT" --foreign-asset $asset_id  \
     --app-account $app_addr --out algo_in_app_1.txn 
    goal clerk send --from="$client" --to="$app_addr" --amount=18000  --out algohandin.txn
    
    cat algohandin.txn algo_in_app_1.txn > combined_handin.txn 
    goal clerk group -i combined_handin.txn -o group_txn_handin.txn 
    goal clerk split -i group_txn_handin.txn -o splitted_handin.txn 
    goal clerk sign -i splitted_handin-0.txn -o signout_handin-0.txn 
    goal clerk sign -i splitted_handin-1.txn -o signout_handin-1.txn 
    cat signout_handin-0.txn signout_handin-1.txn > handin.txn 
    goal clerk dryrun -t handin.txn -o handin.debug --dryrun-dump --dryrun-accounts "$app_addr"
    goal clerk rawsend -f handin.txn
    echo " ----------- PAYMENT FROM BUYER SUCESSFUL ----------- "
}

function asset_handin {
    # asset hand in - VALID
    ret_amount=1
    goal app call --app-id "$app_id" --from "$client" --note "ASSET_HANDIN" --foreign-asset $asset_id  \
     --app-account $app_addr --app-arg "int:$ret_amount" 
    echo " ----------- ASSSET RETURNED FROM BUYER ----------- "
}









